# Generated by Django 5.1.1 on 2024-10-22 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0004_shipping_is_verified_shipping_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('code', models.CharField(blank=True, max_length=8, verbose_name='code')),
                ('is_paid', models.BooleanField(default=None, verbose_name='is paid')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='amount')),
                ('describe', models.TextField(blank=True, verbose_name='describe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_shipping', to='shipping.shipping', verbose_name='shipping')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
                'ordering': ['-updated_at'],
            },
        ),
    ]
