# Generated by Django 5.1.1 on 2024-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
    ]
