# Generated by Django 5.1.1 on 2024-10-21 08:17

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('descibe', models.TextField(blank=True, verbose_name='describe')),
                ('establish', models.CharField(blank=True, max_length=4, verbose_name='establish')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, verbose_name='code')),
                ('product', models.CharField(max_length=100, verbose_name='product')),
                ('weight', models.FloatField(default=0, verbose_name='weight')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='cost')),
                ('source', models.CharField(max_length=50, verbose_name='source')),
                ('destination', models.CharField(max_length=50, verbose_name='destination')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_received', models.BooleanField(default=False, verbose_name='is received')),
                ('describe', models.TextField(blank=True, verbose_name='describe')),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_company', to='shipping.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping',
                'ordering': ['-updated_at'],
            },
        ),
    ]
