# Generated by Django 5.1.1 on 2024-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipping_customer_shipping_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='cost'),
        ),
    ]
