# Generated by Django 5.1.1 on 2024-10-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shipping_is_verified_shipping_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='code',
            field=models.CharField(blank=True, help_text='Auto-generated', max_length=8, verbose_name='code'),
        ),
    ]
