# Generated by Django 5.1.1 on 2024-10-22 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_shipping_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=8, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid'),
        ),
    ]
